### ISSUE TITLE
Custom Keyword implementation example also matches properties

### ISSUE THREAD

**Issue by holgpar** [harrel56/json-schema#101]
Hi,

I followed https://github.com/harrel56/json-schema#adding-custom-keywords to implement a custom keyword. It works, but there can an unintended side-effect:

If somewhere in the schema, a property named "customKeyword" is defined, 

```json
{
   "type": "object",
   "properties": {
       "customKeyword": {
            "type": "string"
       }
   }
}
```

the if statement in the example would match that as well. That can have undesired consequences.
One could probably tweak the if statement by analyzing a location pointer, but maybe there is a better way?

**Comment by harrel56** [comment]
That is indeed a kind of side-effect. The reason for it is that I treat every JSON object the same way and any JSON object can be referred as a separate schema. It doesn't matter if object is located on the top level, in `$defs`, `anyOf` or `properties`. So for example you can have a `$ref` which points to `#/properties` (note that such refs could be invalid in some/most implementations - I believe JSON Schema spec allows such behavior as optional or rather undefined).

But if you don't use such references it should not be a problem because "CustomKeywordEvaluator" won't be run during validation. I guess this might be weird that for such schema "CustomKeywordEvaluator" constructor is invoked.

I think that you shouldn't worry about such cases and don't check for it in the evaluator constructor. Do you see any other problems that can arise from such approach?

**Comment by harrel56** [comment]
Also this behavior isn't specific for just custom keyword. Considering a (part of) meta-schema for draft2020-12:
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://json-schema.org/draft/2020-12/meta/validation",
    "properties": {
        "const": true,
        "enum": {
            "type": "array",
            "items": true
        },
        "multipleOf": {
            "type": "number",
            "exclusiveMinimum": 0
        },
        "maximum": {
            "type": "number"
        },
        "exclusiveMaximum": {
            "type": "number"
        },
        "minimum": {
            "type": "number"
        },
        "exclusiveMinimum": {
            "type": "number"
        },
...
```
Here, keywords which have very specific validation logic are used just as a part of `properties` keyword. You could even refer to it by `https://json-schema.org/draft/2020-12/meta/validation#/properties` (which of course would be stupid thing to do). The way it works is rather simple: for examples `minimum` keyword expects a number as its field value, but here it's a JSON object - in such case creating `minimum` evaluator fails and `EvaluatorFactory` just returns empty optional.

**Comment by holgpar** [comment]
For me (with limited understanding) it comes down to this:

Naively, I would implement a custom keyword like this:


```java
    @Override
    public Optional<Evaluator> create(
        SchemaParsingContext schemaParsingContext,
        String fieldName,
        dev.harrel.jsonschema.JsonNode jsonNode) {
      if ("multiple".equals(fieldName)) {
        // this extracts a property of the keyword
        BigInteger factor = extractFactor(schemaParsingContext);
        return Optional.of(
            (evaluationContext, instanceNode) -> {
              BigInteger value = instanceNode.asInteger();
              return value.mod(factor).longValue() == 0
                  ? Evaluator.Result.failure()
                  : Evaluator.Result.success();
            });
      }
      return Optional.empty();
    }
```

But because the if branch is also executed if somewhere in the schema there is a object construct with a property "multiple", I would move the call to `extractFactor` into the lambda function:

```java
    @Override
    public Optional<Evaluator> create(
        SchemaParsingContext schemaParsingContext,
        String fieldName,
        dev.harrel.jsonschema.JsonNode jsonNode) {
      if ("multiple".equals(fieldName)) {
        return Optional.of(
            (evaluationContext, instanceNode) -> {
              // this extracts a property of the keyword
              BigInteger factor = extractFactor(schemaParsingContext);
              BigInteger value = instanceNode.asInteger();
              return value.mod(factor).longValue() == 0
                  ? Evaluator.Result.failure()
                  : Evaluator.Result.success();
            });
      }
      return Optional.empty();
    }
```

This has the consequence that the instance created by the lambda will hold on to a reference to `schemaParsingContext`. I can imagine that _could_ be an issue for various reasons. What would be your advice in such a situation?

**Comment by harrel56** [comment]
Firstly, (I don't know if you just did for the sake of your example) `extractFactor()` call could be replaced with `jsonNode.asInteger()` so there would be no need for using schema parsing context. The issue here is that `jsonNode` is not guaranteed to be of an integer type (calling this method on non integer type would have undefined behaviour) - so assuming that if `multiple` field has non integer you want to perform no validation at all, I would just add the type check to your if condition: `if ("multiple".equals(fieldName) && jsonNode.isInteger())`.

And yes, using schema parsing context in evaluation logic would not be recommended. This context should only be used during schema parsing process. I would even say that using it differently will have undefined behaviour - but I think there is no way to restrict users from doing that (although the docs could be more clear about it).

**Comment by holgpar** [comment]
Great. Thanks for the advice.
