### ISSUE TITLE
$comment not allowed in properties

### ISSUE THREAD

**Issue by bombaywalla** [harrel56/json-schema#153]
Not sure that this is a bug or defined behavior, but the following schema does not validate.
```json
{
    "$id": "https://example.com/error.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "$comment": "foo",
        "id": { "type": "integer" }
    }
}
```
When I run `registerSchema` on the above schema, I get
```
Execution error (InvalidSchemaException) at dev.harrel.jsonschema.MetaSchemaValidator$DefaultMetaSchemaValidator/validateSchema (MetaSchemaValidator.java:49).                                                              
Schema [https://example.com/error.json] failed to validate against meta-schema [https://json-schema.org/draft/2020-12/schema]                                                                                                                                                                                 
```
In [Draft 2020-12](https://json-schema.org/draft/2020-12/json-schema-core) in Section 10.3.2.1, it says `The value of "properties" MUST be an object. Each value of this object MUST be a valid JSON Schema`.  And, Section 8.3 says `Schema vocabularies SHOULD allow "$comment" within any object containing vocabulary keywords.`.  If I was being pedantic, I'd say that it is reasonable that the the schema I presented above is considered invalid according to the definitions.  But it does seem unexpected.

I've tried searching for a definitive answer but was not able to come up with anything useful.

I've worked around this issue in my schema, but wanted to report it in case others ran into it as well.
I'd appreciate any guidance on whether this is expected behavior or not.

**Comment by harrel56** [comment]
This should be expected behavior. 

`$comment` keyword (and also any other keyword) only makes sense when used directly in a JSON object which is a JSON schema. `/properties` is a JSON object but is not considered a JSON schema - it's just a keyword's body/content. And the content of `properties` keyword has strictly defined structure, as the spec says in a citation you provided.

As per `Schema vocabularies SHOULD allow "$comment" within any object containing vocabulary keywords.` - body of `properties` should not contain any keywords (vocabulary keywords as well) because, again, it's not an instance of a JSON schema.

The only time you would want to put `$comment` in `properties` is when your instance/data to be validated by this schema would actually contain a field named `$comment` - but I understand it's not what you're trying to achieve.

Probably the easiest way for a workaround is to use `withDisabledSchemaValidation` method on validator factory. Also you could write your own modified version of draft2020-12 meta-schema to allow for such cases. But I believe it'd possibly break when your instance/data to be validated actually contained `$comment` field (maybe to avoid this you could write your own version of `PropertiesEvaluator` and handle this edge case accordingly - but this is just going deeper into the rabbit hole).

So I would generally recommend to stay compliant with spec and do not use `$comment` in this place :)

Let me know if this makes sense and if you have any further questions!

**Comment by bombaywalla** [comment]
Thanks.  Sounds reasonable.  The key thing I was missing was "`/properties` is a JSON object but is **not** considered a JSON schema - **it's just a keyword's body/content**." (emphasis mine).

FWIW, the comment I had in `properties` was something to the effect of "Should we add a property called foo?".  In any case, I agree that it's better to be compliant, and I moved the comment.

Thanks again.  And thanks for the library.

**Comment by bombaywalla** [comment]
Closing this issue.
